### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Krinkle** [overset/javascript-natural-sort#28]
Hi,

I haven't looked into the details yet, but I notice that a quick comparison to [natural-compare-lite](https://github.com/litejs/natural-compare-lite) shows that they are pretty similar with the latter over twice as fast.

``` js
// var naturalSort = overset/javascript-natural-sort
var start = performance.now(); var i = 100000;
while(i--) ['param10', 'param9', 'param2'].sort(naturalSort);
performance.now() - start; // 1841.664… ms

var start = performance.now(); var i = 100000;
while(i--) ['param10', 'param9', 'param2'].sort(naturalSort);
performance.now() - start; // 1859.729… ms

// var naturalCompare = litejs/natural-compare-lite
var start = performance.now(); var i = 100000;
while(i--) ['param10', 'param9', 'param2'].sort(naturalCompare);
performance.now() - start; // 675.659… ms

var start = performance.now(); var i = 100000;
while(i--) ['param10', 'param9', 'param2'].sort(naturalCompare);
performance.now() - start; // 667.669… ms
```

While this may be because of the extra features (special-casing of float strings and date strings), it seems worth a look to see if some optimisations can be made.

Aside from the float and date values, natural-compare-lite produces the same results for the examples in the [readme](https://github.com/overset/javascript-natural-sort#readme).

**Comment by overset** [comment]
@Krinkle good to know! I haven't done a side-by-side comparison on `natural-compare-lite` but it's definitely worth doing a bit of optimization. After some quick profiling the `normChunk` and `i` nested functions take up a bit of the runtime. A lot of the regex and brute-force type inference could be optimized as well without sacrificing backward compatibility. I've intended to add significantly more tests to http://overset.github.io/javascript-natural-sort/unit-tests.html and draw some comparisons for other offerings including `localeCompare()` implementations.
