### ISSUE TITLE
Odd bug

### ISSUE THREAD

**Issue by conradks** [overset/javascript-natural-sort#33]
I haven't had any issues with sorting until I tried to sort the following array:
`['Facebook','local host 1025 pt2','11111','hello','Local host 20546','127 1025','Local Hosters 1']`
The result is:
`["127 1025", "11111", "Facebook", "Local Hosters 1", "Local host 20546", "hello", "local host 1025 pt2"]`
This problem only occurred with v0.8.1. I used an older version I found in some old code I had, and it sorted properly:
`["127 1025", "11111", "Facebook", "hello", "local host 1025 pt2", "Local host 20546", "Local Hosters 1"]`

**Comment by overset** [comment]
@conradks - sounds like the case sensitivity that was added and try setting the `naturalSort.insensitive = true;`. Example for both v0.8 and v0.8.1:
```javascript
>>> ['Facebook','local host 1025 pt2','11111','hello','Local host 20546','127 1025','Local Hosters 1'].sort(naturalSort)
["127 1025", "11111", "Facebook", "Local Hosters 1", "Local host 20546", "hello", "local host 1025 pt2"]
>>> naturalSort.insensitive = true;
>>> ['Facebook','local host 1025 pt2','11111','hello','Local host 20546','127 1025','Local Hosters 1'].sort(naturalSort)
["127 1025", "11111", "Facebook", "hello", "local host 1025 pt2", "Local host 20546", "Local Hosters 1"]
```

**Comment by conradks** [comment]
Seems to work. Thank you for the prompt response.
