### ISSUE TITLE
Unit Tests fail on Chrome

### ISSUE THREAD

**Issue by vankooch** [overset/javascript-natural-sort#7]
Hi,

Thank you for your work. Sadly for me the unit tests on Chrome do not work. I've tested on Windows 7 and Mac OS X 10.7.5. On both machines Chrome runs on latest stable version which is: Version 22.0.1229.94

Windows:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4
Mac:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4

Error is on both machines the same:

```error
contributed tests (1, 6, 7)
Source: 	
    at wrapTest (file://localhost/Users/Downloads/overset-javascript-natural-sort-dbf4ca2/unit-tests.html?testNumber=13:368:4)
    at Object.<anonymous> (file://localhost/Users/Downloads/overset-javascript-natural-sort-dbf4ca2/unit-tests.html?testNumber=13:355:17)
issue #5 - invalid sort order - Howie Schecter - [ "9", "11", "22", "99", "A", "aaaa", "bbbb", "Aaaa", "aAaa", "aa", "AA", "Aa", "aA", "BB", "bB", "aaA", "AaA", "aaa" ]

```

Please let me know If you need more debug infos.

Thank you!

**Comment by overset** [comment]
The sort for that case is working now and tested in Chrome 45
